Support negative observations
smartcontractkit/chainlink-terra pull request #165
Opened 2022-03-02 16:28 UTC by connorwstein

2022-03-02 17:16 UTC, aalu1418 requested changes
Also just a general question: where should we store this helper?

if we wanted to use this in chainlink-solana...would the imports get weird?

2022-03-02 17:16 UTC, aalu1418 commented on pkg/terra/marshal_signed_int.go
> +	negative := o.Sign() < 0
should this have validation that the big.Int fits in the expected number of bytes?

like in libocr: https://github.com/smartcontractkit/libocr/blob/449836e6cfec324fbd6781e9a4d4b953840cdf0b/offchainreporting2/reportingplugin/median/observation.go#L21

2022-03-02 17:16 UTC, aalu1418 commented on pkg/terra/marshal_signed_int.go
> +	maxPositive := big.NewInt(0).Sub(big.NewInt(0).Lsh(big.NewInt(1), numBits-1), big.NewInt(1))
could separate this into another helper func so we can use it in both functions

2022-03-02 17:20 UTC, jmank88 submitted a review, later dismissed

2022-03-03 19:16 UTC, connorwstein commented
> Also just a general question: where should we store this helper?
> 
> if we wanted to use this in chainlink-solana...would the imports get weird?

I'll try to just PR this to OCR

2022-03-04 15:52 UTC, aalu1418 approved these changes
🎉

2022-03-04 16:12 UTC, merged