Add Explicit Names For CI
smartcontractkit/chainlink-terra pull request #241
Opened 2022-03-29 13:36 UTC by tateexon

2022-03-29 15:15 UTC, krebernisak approved these changes

2022-03-29 15:15 UTC, krebernisak commented on .github/workflows/chaos.yml
> +  E2E_Chaos_Build_Custom_Chainlink_Image:
Do these actually show anywhere now that we have explicit names for all?

I'd prefer we leave them lowercase, to follow the rest of `yml` workflow style, but we should make sure to add an explicit name for each.

2022-03-29 15:15 UTC, krebernisak commented on .github/workflows/gauntlet.yml
>            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
Please also remove the `NPM_TOKEN` setup from workflows, as `gautlet-core` should now be public so this shouldn't be necessary anymore.

2022-03-29 15:15 UTC, krebernisak commented on .github/workflows/golangci-lint.yml
> +      - '**.go'
Will this only run if `'**.go'` files are touched?

If that's the case, then we can't enable this as a global check for develop branch. Consider removing this filter, for now, so we enable this check globally.

2022-03-30 11:00 UTC, krebernisak requested changes

2022-04-01 20:42 UTC, aalu1418 requested changes

2022-04-01 20:42 UTC, aalu1418 commented on .github/workflows/gauntlet.yml
> +    name: Guantlet Build
```suggestion
    name: Gauntlet Build
```

2022-04-01 20:47 UTC, tateexon commented on .github/workflows/gauntlet.yml
> +    name: Guantlet Build
🤦

2022-04-01 20:56 UTC, aalu1418 approved these changes

2022-04-02 09:12 UTC, krebernisak commented on .github/workflows/chaos.yml
> +name: e2e_chaos_tests
Why the discrepancy from Solana? What was the problem when using nix there?

2022-04-02 14:27 UTC, tateexon commented on .github/workflows/chaos.yml
> +name: e2e_chaos_tests
Nix on Solana had a 1 hour cache issue for the first call using it for every run. We don't have that for Terra. When we solve that cache issue for nix on Solana have it use nix as well.

2022-04-04 18:59 UTC, aalu1418 approved these changes

2022-04-05 15:46 UTC, krebernisak approved these changes

2022-04-05 15:46 UTC, krebernisak commented on .golangci.yml
> +      # - name: exported
We should document all Go exported (public) types

2022-04-05 15:55 UTC, merged